version: "3.3"

services:

  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  core_api:
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.core_api.rule=Host(`core_api.example.com`)"
      - "traefik.http.routers.core_api.entrypoints=websecure"
      - "traefik.http.routers.core_api.tls.certresolver=myresolve"
    ports:
      - "8000:15400"
    volumes:
      - ./app/:/app  
